---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: wordpress
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: mariadb
automountServiceAccountToken: true