apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
  namespace: {{ .Values.namespace }}
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.odoo.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.odoo.persistence.size }}