apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.wordpress }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: wordpress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.mariadb }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true
