apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: wordpress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP