apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}