apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-sites
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frappe
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.sites.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.sites.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-logs
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frappe
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-redis-cache-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frappe
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.redis.cache.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.cache.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-redis-queue-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frappe
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.redis.queue.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.queue.persistence.size }}