apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frappe
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true