apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mautic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitea.nav.ovh/Maha_Msadak/devsecops-navitrends.git
    targetRevision: ubuntu-server
    path: k8s/charts/mautic
  destination:
    server: https://kubernetes.default.svc
    namespace: mautic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
