apiVersion: v1
kind: Service
metadata:
  name: mautic-mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: mautic-mariadb
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # clusterIP: None = headless. No virtual IP assigned.
  # Required for StatefulSet stable DNS entries.
  clusterIP: None
  selector:
    app: mautic-mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
      protocol: TCP
