apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: {{ .Values.namespace }}
  labels:
    app: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.nextcloud.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.nextcloud.persistence.size }}