apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: {{ .Values.namespace }}
  labels:
    app: nextcloud
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP