namespace: odoo

serviceAccount:
  name: odoo

vault:
  role: odoo
  secretPath: secret/data/odoo
  secretFile: config

odoo:
  image:
    repository: odoo
    tag: "18.0"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "10m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  persistence:
    size: 10Gi
    storageClass: local-path
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10

postgres:
  image:
    repository: postgres
    tag: "15.10"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "10m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    size: 10Gi
    storageClass: local-path
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 5