apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: {{ .Values.namespace }}
  labels:
    app: n8n
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.n8n.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
