apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: {{ .Values.namespace }}
  labels:
    app: n8n
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - name: http
      port: 5678
      targetPort: 5678
      protocol: TCP
