apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: n8n-postgres
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: n8n-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
